apiVersion: config.openshift.io/v1
kind: Infrastructure
metadata:
  name: cluster
spec:
  cloudConfig:
    name: ""
  platformSpec:
    aws: {}
    type: Azure
status:
  apiServerURL: https://ca-saint-john-dns-04137031.hcp.canadaeast.azmk8s.io:443 
